version: "3.7"

services:
  php:
    #image: "php:8.0.2-apache-buster"    
    build:       
      dockerfile: "./docker/php-docker-with-composer"
      context: .
    volumes: 
      - "./kode:/var/www/html"
    working_dir: "/kode"
    #entrypoint: "service apache2 start && tail -f /dev/stdout"
    # ports: 
    #   - "9554:80"

  php2:    
    build:       
      dockerfile: "./docker/php-docker-with-composer"
      context: .
    volumes: 
      - "./laravel_sample:/var/www/html"
      - "./apache:/etc/apache2/sites-available"
    working_dir: "/kode"

  database:
    image: "mysql:5.6.49"
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=qwikfix_local

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  proxy:
    image: "nginx:latest"
    volumes:
      - "./nginx:/etc/nginx/conf.d"
    # volumes_from: 
    #   - php
    depends_on: 
      - php
    ports:
      - "9555:80"
      - "9556:81"


