version: "3.7"

services:
  php:    
    build:       
      dockerfile: "./application/sandbox/docker/php-docker-with-composer"
      context: .
    volumes: 
      - "./application/sandbox/marvel_app/marvel_app_kode:/var/www/html"
      - "./apache:/etc/apache2/sites-available"
    working_dir: "/kode"

  database:
    image: "mysql:5.6.49"
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=jeff_local

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment: 
      - ADMINER_DESIGN=dracula

  proxy:
    image: "nginx:latest"
    volumes:
      - "./nginx:/etc/nginx/conf.d"    
    depends_on: 
      - php
    ports:
      - "9555:80"      


