name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    env:
      TESTZEBRA: ablkj
    steps:
      - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
        with:
          php-version: '7.2'
      - uses: actions/checkout@v2
      - name: Show Dir Structure
        run: ls -la    
      - name: Copy .env
        working-directory: ./application/sandbox/marvel_app/marvel_app_kode
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        working-directory: ./application/sandbox/marvel_app/marvel_app_kode
        run: ls -la  && composer install -q --no-ansi --no-interaction --no-scripts
      - name: Generate key
        working-directory: ./application/sandbox/marvel_app/marvel_app_kode
        run: php artisan key:generate
      - name: Directory Permissions
        working-directory: ./application/sandbox/marvel_app/marvel_app_kode
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        working-directory: ./application/sandbox/marvel_app/marvel_app_kode
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Show Environment
        run: env
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        working-directory: ./application/sandbox/marvel_app/marvel_app_kode
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
          HOSTNAME: TestFooBar
        run: vendor/bin/phpunit --testdox
  deploy-qat:
    needs: [laravel-tests]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./application/sandbox/marvel_app/marvel_app_kode
    env:
      TESTZEBRA: ablkj
    steps:
      - uses: actions/checkout@v2
      - uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:          
          # ftp server
          server: qat.app.theqwikfix.com
          # ftp username
          username: git_jeff_ftp_qat@qat.app.theqwikfix.com
          # ftp password
          password: sNhkX5vLP9QYMwWX
          # Server port to connect to (read your web hosts docs)
          port: 21 # optional
          # protocol to deploy with - ftp, ftps, or ftps-legacy
          protocol: ftps # optional
          # Folder to upload from, must end with trailing slash /
          local-dir: ./application/sandbox/marvel_app/marvel_app_kode/test_ftp/ # optional
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: /sub_folder/ # optional
          # Path and name of the state file - this file is used to track which files have been deployed
          state-name: # optional
          # Prints which modifications will be made with current config options, but doesnt actually make any changes
          dry-run: true # optional
          # Deletes ALL contents of server-dir, even items in excluded with exclude argument
          dangerous-clean-slate: false # optional
          # An array of glob patterns, these files will not be included in the publish/delete process
          exclude: # optional
          # How verbose should the information be - warn, info, debug
          log-level: verbose # optional
          # strict or loose
          security: # optional
